apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer  # Change to NodePort or ClusterIP if needed
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80 # Node Port 80 For Container Port 80
    targetPort: 80
